services:
  floorball:
    build: .
    container_name: floorball-stats-tracker
    ports:
      - "5000:5000"
    volumes:
      - ./gamesFiles/:/app/gamesFiles/
      - ./rosters/:/app/rosters/
      - ./logs/:/app/logs/
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
